---
- name: Install nginx
  hosts: host.name.ip
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present
  - name: Insert Index Page
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html
  - name: Make ssl directory
    file:
      path: etc/ssl/private
      state: directory
      mode: 700
      
  - name: Start NGiNX
    service:
      name: nginx
      state: started
  - name: Install MySQL Database
    yum:
      name: mysql-community-server
      state: present
  - name: Configure MySQL Database
    service:
      name: mysqld
      state: started
      
